services:
  - type: web
    name: heart-disease-mlops-api
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
